#!/usr/bin/env sh
. "$(dirname -- "$0")/husky.sh"

message="$(cat $1)"
requiredPattern="^(test|add|cut|fix|bump|make|start|stop|refactor|reformat|optimise|document|merge) .*$"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format: <verb in imperative mood> <what was done>"
  echo "Allowed verbs in imperative mood: [test, add, cut, fix, bump, make, start, stop, refactor, reformat, optimise, document, merge"]
  echo "Example: add testing commit"
  echo "-"
  echo "Your commit message was: $message"
  exit 1
fi
